version: "2"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./node_modules/.bin/nodemon server.js 
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 80:80
